language: "es_core_news_sm"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"