language: "es_core_news_sm"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"

policies:
  - name: KerasPolicy
    max_history: 5
    epochs: 100
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
    nlu_threshold: 0.2
    core_threshold: 0.1
    fallback_action_name: 'utter_no_te_entiendo'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy